name: Docker Image CI

on:
  push:
    branches: ["production"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login --username bappeda-dev-team --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/bappeda-dev-team/survey-app:latest
          docker push ghcr.io/bappeda-dev-team/survey-app:latest
